### ISSUE TITLE
Chapter 1 - Exam Set A clarifications.

### ISSUE THREAD

**Issue by abutohan** [jalizadeh/ISTQB-Exam-Questions#1]
Hi Javad,

Thank you so much for these questionnaires, these are great for reviewing ISTQB CTFL.

However, I just have some clarifications for some of the questions in Chapter 1 Set A.

On question 7) Which is the best definition of complete testing:
The correct answer that was provided is A. You have discovered every bug in the program.
Was it conflicting one of the 7 testing principle? Exhaustive testing is impossible?

On question 21) Which one is not comes under international standard.
The correct answer that was provided is B. IEEE.
However, IEEE was also included in CTFL syllabus as one of the international standard.

On question 23) Majority of system errors occur in the _________ phase
The correct answer that was provided is A. Requirements Phase
I'm not quite sure about this one, but the question includes the keyword "system errors". Was the system under test is already built and might be the best answer could be testing phase?

Lastly, on question 39, The correct answer that was provided is E.
However the choices are only A-D.

Hoping you could clarify these concerns of mine. Thank you!

**Comment by jalizadeh** [comment]
Hi Abutohan,
thanks for noticing and mentioning the doubts. At the time I collected these questions, I was still studying and getting prepared with any sort of questions was available publicly. Most of these questions are now far outdated as the reference has been updated and will be updated soon again. And as you will notice again, there are more confilcts between the different set of questions. As I couldnt find the exact source of the questions, I can not surely respond which is the correct answer.

After the exam, I created a new repository which I guess can be more helpful https://github.com/jalizadeh/ISTQB-CTFL
